server:
  port: ${easyflow.ecosystem.social-service.port}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social
    username: easyflow
    password: easyflow
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:migrations/social
    url: jdbc:postgresql://localhost:5432/social
    user: easyflow
    password: easyflow
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
  jpa:
    generate-ddl: off
    database: postgresql
    hibernate:
      ddl-auto: validate
  cloud:
    openfeign:
      client:
        config:
          authClient:
            url: "${easyflow.ecosystem.auth-service.url}"

easyflow:
  ecosystem:
    auth-service:
      url: http://127.0.0.1:8095
      domain: 127.0.0.1
      port: 8095
    social-service:
      url: http://127.0.0.1:8100
      domain: 127.0.0.1
      port: 8100
    user-service:
      url: http://127.0.0.1:8105
      domain: 127.0.0.1
      port: 8105