server:
  port: ${easyflow.ecosystem.user-service.port}
spring:
  application:
    name: "user-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: easyflow
    password: easyflow
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:migrations/users
    url: jdbc:postgresql://localhost:5432/users
    user: easyflow
    password: easyflow
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
  jpa:
    generate-ddl: off
    database: postgresql
    hibernate:
      ddl-auto: validate
  cloud:
    openfeign:
      client:
        config:
          authClient:
            url: "${easyflow.ecosystem.auth-service.url}"
          taskClient:
            url: "${easyflow.ecosystem.task-service.name}"
#  main:
#    web-application-type: servlet

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    path: /swagger

easyflow:
  ecosystem:
    auth-service:
      url: http://127.0.0.1:8095
      domain: 127.0.0.1
      port: 8095
    social-service:
      url: http://127.0.0.1:8100
      domain: 127.0.0.1
      port: 8100
    user-service:
      url: http://127.0.0.1:8105
      domain: 127.0.0.1
      port: 8105
    task-service:
      url: http://127.0.0.1:8110
      domain: 127.0.0.1
      port: 8110
      name: http://task-service